### ISSUE TITLE
neuron: cannot import name 'neuron_kernel' from 'modules'

### ISSUE THREAD

**Issue by chococheri** [pkuxmq/OTTT-SNN#2]
I already installed the spikingjelly in another place,  but cannot find the neuron_kernel and neuron_kernel. the relevant errors are as follows. Looking forward to your reply, thank you!
 
```python
/home/qtt/Software/anaconda3/bin/python /home/qtt/PycharmProjects/OTTT_SNN/train_cifar.py -data_dir /home/qtt/PycharmProjects/cifar10 -dataset cifar10 -out_dir log_checkpoint_cifar10 -gpu-id 0 
neuron: cannot import name 'neuron_kernel' from 'modules' (
![1](https://user-images.githubusercontent.com/38455510/212277523-da32553c-aaa4-447f-a86a-9b7495d83037.png)
unknown location)
Traceback (most recent call last):
  File "/home/qtt/PycharmProjects/OTTT_SNN/train_cifar.py", line 21, in <module>
    from torchtoolbox.transform import Cutout
  File "/home/qtt/Software/anaconda3/lib/python3.9/site-packages/torchtoolbox/transform/__init__.py", line 5, in <module>
    from .autoaugment import *
  File "/home/qtt/Software/anaconda3/lib/python3.9/site-packages/torchtoolbox/transform/autoaugment.py", line 194, in <module>
    Compose([Posterize(0.4, 8), Rotate(0.6, 9)]),
  File "/home/qtt/Software/anaconda3/lib/python3.9/site-packages/torchtoolbox/transform/autoaugment.py", line 104, in __init__
    ranges = np.round(np.linspace(8, 4, 10), 0).astype(np.int)
  File "/home/qtt/Software/anaconda3/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
```
![1](https://user-images.githubusercontent.com/38455510/212280914-0466873f-ac34-4384-b885-5507c85e6b9b.png)

**Comment by pkuxmq** [comment]
Hi, you can comment out the "try: ... except..." sentences and directly write "neuron_kernel = None". The released code does not directly depend on the spikingjelly package. I have copied some source files from spikingjelly and put them in the code in order to avoid dependency on the package (because I note that spikingjelly is updated frequently and some different versions may not be compatible with each other). This neuron_spikingjelly.py file is directly copied from the repository, while some files such as "neuron_kernel" or "cu_kernel_opt" are not copied because I do not use them in the code. So there could be the error that these files are not found. I will also update the repository for this change.

**Comment by chococheri** [comment]
Thank you for getting back to me. The error is already resolved!
